baseURL: "https://ergoalejandro.github.io/"
title: ErgoAlejandro
paginate: 5
theme: PaperMod

canonifyURLs: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Ergo Alejandro
    description: "Blog y muro personal de Ergo Alejandro"
    keywords: [Blog, Portfolio, PaperMod, Linux, Mac, Dise침o, Audiovisual]
    author: Me
    # author: ["Ergo", "Alejandro"] # multiple authorses
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    # defaultTheme: light
    # defaultTheme: dark
    defaultTheme: auto # to switch between dark or light according to browser theme
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://i.imgur.com/YzWivD1.png"
        favicon16x16: "https://i.imgur.com/YzWivD1.png"
        favicon32x32: "https://i.imgur.com/YzWivD1.png"
        apple_touch_icon: "https://i.imgur.com/YzWivD1.png"
        safari_pinned_tab: "https://i.imgur.com/YzWivD1.png"

    label:
        text: "@ergoalejandro"
        icon: "https://i.imgur.com/FrJsivg.png"
        iconHeight: 34

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: "Soy Ergo Alejandro \U0001f996"
        subtitle: "Dise침o Grafico publicitario y Comunicaci칩n Audiovisual en Peru"
        imageUrl: "https://i.imgur.com/OT4bvEh.png"
        imageWidth: 120
        imageHeight: 120
        imageTitle: "Federgo tux"
        buttons:
            - name: Proyectos
              url: proyectos
            - name: Blog
              url: blog
            - name: Sobre Mi
              url: sobremi

# home-info mode
    homeInfoParams:
        Title: "Soy Ergo Alejandro \U0001f996"
        Content: "Estudiante de Comunicaci칩n Audiovisual alojado en Peru"

    socialIcons:
        - name: github
          url: "https://github.com/ErgoAlejandro"
        - name: twitter
          url: "https://twitter.com/ergoalejandro"
        - name: youtube
          url: "https://www.youtube.com/channel/UCP45j6KPoaKo-fRNrQbwfJA"
        - name: email
          url: "mailto:ergoalejandro2004@gmail.com"
        - name: mastodon
          url: "https://mastodon.la/@ergoalejandro"
menu:
    main:
        - identifier: Proyectos
          name: Proyectos
          url: /proyectos/
          weight: 10
        - identifier: Blog
          name: Blog
          url: /blog/
          weight: 20
        - identifier: Sobre Mi
          name: Sobre Mi
          url: /sobremi/
          weight: 20              

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
